# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
---
title: StartPage
theme: dark
color: purple
target: _blank
language: en
headerStyle: boxed

layout:
  Media:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
